import { useRef, useEffect } from 'react';
import { useMyPayslips } from '../../../../hooks/useERPApi';

const C = {
  orange: '#C9883A', orangeGrad: 'linear-gradient(145deg, #e8a84e 0%, #C9883A 100%)',
  cream: '#F8F7F4', white: '#FFFFFF', dark: '#1A1A1A', muted: '#6B6B6B',
  border: 'rgba(0,0,0,0.07)',
};

// Animated gradient orbs hero
function OrbHero() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const rafRef    = useRef<number>(0);
  useEffect(() => {
    const c = canvasRef.current; if (!c) return;
    const ctx = c.getContext('2d'); if (!ctx) return;
    c.width = c.offsetWidth; c.height = c.offsetHeight;
    const W = c.width; const H = c.height;
    let t = 0;
    function draw() {
      ctx!.clearRect(0, 0, W, H);
      [[0.3,0.5,90,'rgba(201,136,58,0.12)'],[0.7,0.4,70,'rgba(99,102,241,0.09)'],[0.5,0.7,80,'rgba(16,185,129,0.07)']].forEach(([fx, fy, r, clr], i) => {
        const x = (fx as number) * W + Math.sin(t * 0.5 + i * 2) * 30;
        const y = (fy as number) * H + Math.cos(t * 0.4 + i) * 20;
        const g = ctx!.createRadialGradient(x, y, 0, x, y, r as number);
        g.addColorStop(0, clr as string);
        g.addColorStop(1, 'rgba(0,0,0,0)');
        ctx!.fillStyle = g;
        ctx!.fillRect(0, 0, W, H);
      });
      t += 0.012;
      rafRef.current = requestAnimationFrame(draw);
    }
    draw();
    return () => cancelAnimationFrame(rafRef.current);
  }, []);
  return <canvas ref={canvasRef} style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', pointerEvents: 'none' }} />;
}

const STATUS_COLORS: Record<string, string> = { draft: '#f59e0b', approved: '#10b981', paid: '#6366f1' };
const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];

function downloadPayslip(row: any) {
  const content = `
XERXEZ ERP — PAYSLIP
====================
Employee : ${row.employee_name} (${row.employee_code})
Period   : ${MONTHS[row.month - 1]} ${row.year}
Status   : ${row.status.toUpperCase()}
-------------------
Working Days : ${row.working_days}
Present Days : ${row.present_days}
-------------------
Basic Salary : $${parseFloat(row.basic).toFixed(2)}
Allowances   : $${parseFloat(row.allowances).toFixed(2)}
Deductions   : -$${parseFloat(row.deductions).toFixed(2)}
Gross Salary : $${parseFloat(row.gross).toFixed(2)}
NET SALARY   : $${parseFloat(row.net_salary).toFixed(2)}
-------------------
${row.paid_at ? `Paid On : ${new Date(row.paid_at).toLocaleDateString()}` : 'Payment Pending'}
====================
Generated by XERXEZ ERP
  `.trim();
  const blob = new Blob([content], { type: 'text/plain' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `Payslip_${row.employee_name.replace(/\s+/g, '_')}_${MONTHS[row.month-1]}_${row.year}.txt`;
  a.click();
}

export default function MyPayslipsModule() {
  const { data, loading, error } = useMyPayslips();

  return (
    <div style={{ animation: 'mpFadeUp 0.45s ease both' }}>
      <style>{`@keyframes mpFadeUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}`}</style>

      {/* Hero */}
      <div style={{
        position: 'relative', borderRadius: 18, overflow: 'hidden', marginBottom: 28,
        background: 'linear-gradient(135deg, #1a1208 0%, #2d1e08 50%, #0f0a05 100%)',
        padding: '26px 32px 24px',
        boxShadow: '0 8px 32px rgba(0,0,0,0.18)',
      }}>
        <OrbHero />
        <div style={{ position: 'relative', zIndex: 1 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
            <div style={{ width: 32, height: 32, borderRadius: 9, background: C.orangeGrad, display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 3px 0 rgba(150,95,30,0.5)' }}>
              <i className="fas fa-file-alt" style={{ color: '#fff', fontSize: 13 }} />
            </div>
            <span style={{ color: 'rgba(255,255,255,0.40)', fontSize: 11, fontFamily: "'DM Sans', sans-serif", fontWeight: 700, letterSpacing: '0.16em', textTransform: 'uppercase' }}>My Payslips</span>
          </div>
          <h2 style={{ color: '#fff', fontFamily: "'DM Sans', sans-serif", fontWeight: 800, fontSize: 24, margin: 0, letterSpacing: '-0.02em' }}>Payslip History</h2>
          <p style={{ color: 'rgba(255,255,255,0.40)', fontSize: 13, fontFamily: "'DM Sans', sans-serif", margin: '6px 0 0' }}>
            Download your monthly payslips — real data from the payroll system
          </p>
          <div style={{ marginTop: 16, display: 'flex', gap: 24 }}>
            <div>
              <div style={{ fontSize: 10, color: 'rgba(255,255,255,0.35)', fontFamily: "'DM Sans', sans-serif", fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase' }}>Total Payslips</div>
              <div style={{ color: '#e8a84e', fontFamily: "'DM Sans', sans-serif", fontWeight: 800, fontSize: 22 }}>{data.length}</div>
            </div>
            {data.length > 0 && (
              <div>
                <div style={{ fontSize: 10, color: 'rgba(255,255,255,0.35)', fontFamily: "'DM Sans', sans-serif", fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase' }}>Latest Net Salary</div>
                <div style={{ color: '#34d399', fontFamily: "'DM Sans', sans-serif", fontWeight: 800, fontSize: 22 }}>
                  ${parseFloat(data[0].net_salary || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Payslip cards grid */}
      {loading ? (
        <div style={{ padding: 64, textAlign: 'center' }}><div className="spinner-border" style={{ color: C.orange }} /></div>
      ) : error ? (
        <div style={{ background: 'rgba(239,68,68,0.07)', border: '1px solid rgba(239,68,68,0.22)', borderRadius: 12, padding: '14px 18px', color: '#ef4444', fontFamily: "'DM Sans', sans-serif" }}>{error}</div>
      ) : data.length === 0 ? (
        <div style={{ background: C.white, borderRadius: 14, border: `1px solid ${C.border}`, padding: 64, textAlign: 'center', color: C.muted, fontFamily: "'DM Sans', sans-serif" }}>
          <i className="fas fa-file-invoice-dollar" style={{ fontSize: 36, display: 'block', marginBottom: 14, color: '#ddd' }} />
          No payslips generated yet. Contact HR to generate payroll.
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: 18 }}>
          {data.map((r: any, idx: number) => {
            const sc = STATUS_COLORS[r.status] ?? C.muted;
            return (
              <div key={r.id}
                style={{
                  background: C.white, borderRadius: 16, border: `1px solid ${C.border}`,
                  overflow: 'hidden', boxShadow: '0 1px 4px rgba(0,0,0,0.05)',
                  transition: 'transform 0.22s, box-shadow 0.22s',
                  animation: `mpFadeUp 0.45s cubic-bezier(0.22,1,0.36,1) ${idx * 0.06}s both`,
                }}
                onMouseEnter={e => { (e.currentTarget as HTMLDivElement).style.transform = 'translateY(-4px)'; (e.currentTarget as HTMLDivElement).style.boxShadow = '0 12px 28px rgba(0,0,0,0.11)'; }}
                onMouseLeave={e => { (e.currentTarget as HTMLDivElement).style.transform = ''; (e.currentTarget as HTMLDivElement).style.boxShadow = '0 1px 4px rgba(0,0,0,0.05)'; }}
              >
                {/* Card header */}
                <div style={{ background: `linear-gradient(135deg, #1a1208, #2d1e08)`, padding: '16px 20px', position: 'relative' }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <div>
                      <div style={{ color: 'rgba(255,255,255,0.45)', fontSize: 10, fontFamily: "'DM Sans', sans-serif", fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase' }}>
                        {MONTHS[r.month - 1]} {r.year}
                      </div>
                      <div style={{ color: '#fff', fontFamily: "'DM Sans', sans-serif", fontWeight: 800, fontSize: 20, marginTop: 2 }}>
                        ${parseFloat(r.net_salary || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                      </div>
                      <div style={{ color: 'rgba(255,255,255,0.38)', fontSize: 11.5, fontFamily: "'DM Sans', sans-serif", marginTop: 2 }}>Net Salary</div>
                    </div>
                    <div style={{ width: 40, height: 40, borderRadius: 11, background: C.orangeGrad, display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 3px 10px rgba(201,136,58,0.35)' }}>
                      <i className="fas fa-file-alt" style={{ color: '#fff', fontSize: 15 }} />
                    </div>
                  </div>
                </div>

                {/* Card body */}
                <div style={{ padding: '16px 20px' }}>
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 14 }}>
                    {[
                      { label: 'Basic', val: `$${parseFloat(r.basic||0).toLocaleString()}`, color: C.dark },
                      { label: 'Allowances', val: `+$${parseFloat(r.allowances||0).toLocaleString()}`, color: '#3b82f6' },
                      { label: 'Deductions', val: `-$${parseFloat(r.deductions||0).toLocaleString()}`, color: '#ef4444' },
                      { label: 'Days', val: `${r.present_days}/${r.working_days}`, color: C.muted },
                    ].map(item => (
                      <div key={item.label}>
                        <div style={{ fontSize: 10, fontWeight: 700, color: C.muted, fontFamily: "'DM Sans', sans-serif", letterSpacing: '0.08em', textTransform: 'uppercase' }}>{item.label}</div>
                        <div style={{ fontFamily: "'DM Sans', sans-serif", fontWeight: 700, fontSize: 14, color: item.color, marginTop: 2 }}>{item.val}</div>
                      </div>
                    ))}
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, padding: '3px 9px', borderRadius: 20, background: `${sc}18`, color: sc, fontSize: 11, fontWeight: 700, fontFamily: "'DM Sans', sans-serif", textTransform: 'capitalize' }}>
                      <span style={{ width: 5, height: 5, borderRadius: '50%', background: 'currentColor', flexShrink: 0 }} />{r.status}
                    </span>
                    <button onClick={() => downloadPayslip(r)}
                      style={{ background: C.orangeGrad, color: '#fff', border: 'none', borderRadius: 9, padding: '7px 14px', fontFamily: "'DM Sans', sans-serif", fontWeight: 700, fontSize: 12, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6, boxShadow: '0 2px 0 rgba(150,95,30,0.5)' }}>
                      <i className="fas fa-download" style={{ fontSize: 11 }} />Download
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
