const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];

/** Generates and downloads a one-page payslip PDF. jsPDF is loaded on demand to keep it
 * out of the main ERP bundle — it's only needed when a user actually downloads one.
 * Allowance/deduction line items come from the employee's current SalaryStructure — Payroll
 * itself only stores the aggregate totals used in that month's calculation, not an itemized
 * snapshot, so the breakdown reflects the structure as it stands today. */
export async function downloadPayslipPDF(payroll: any, salaryStructure: any, formatAmount: (v: number | string) => string) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF();
  const left = 18;
  let y = 20;

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(201, 136, 58);
  doc.text('XERXEZ', left, y);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Payslip', 192, y, { align: 'right' });
  if (payroll.company_name) {
    y += 5;
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(payroll.company_name, 192, y, { align: 'right' });
    doc.setTextColor(0, 0, 0);
  }
  y += 7;
  doc.setDrawColor(201, 136, 58);
  doc.setLineWidth(0.6);
  doc.line(left, y, 192, y);
  y += 10;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Employee Details', left, y);
  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Name: ${payroll.employee_name}`, left, y);
  doc.text(`Employee ID: ${payroll.employee_code}`, 110, y);
  y += 6;
  doc.text(`Department: ${payroll.department_name || '—'}`, left, y);
  doc.text(`Designation: ${payroll.employee_designation || '—'}`, 110, y);
  y += 6;
  doc.text(`Pay Period: ${MONTHS[payroll.month - 1]} ${payroll.year}`, left, y);
  y += 6;
  doc.text(`Working Days: ${payroll.working_days}    Present Days: ${payroll.present_days}`, left, y);
  y += 12;

  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(left, y, 192, y);
  y += 9;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.text('Earnings', left, y);
  doc.text('Deductions', 110, y);
  const headerY = y;
  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('Basic Salary', left, y);
  doc.text(formatAmount(payroll.basic), 95, y, { align: 'right' });

  const allowances: Record<string, number> = salaryStructure?.allowances || {};
  const deductions: Record<string, number> = salaryStructure?.deductions || {};
  let earnY = y;
  Object.entries(allowances).forEach(([name, amount]) => {
    earnY += 6;
    doc.text(name, left, earnY);
    doc.text(formatAmount(amount), 95, earnY, { align: 'right' });
  });

  let dedY = headerY + 7;
  if (Object.keys(deductions).length === 0) {
    doc.setTextColor(140, 140, 140);
    doc.text('None', 110, dedY);
    doc.setTextColor(0, 0, 0);
  } else {
    Object.entries(deductions).forEach(([name, amount]) => {
      doc.text(name, 110, dedY);
      doc.text(formatAmount(amount), 190, dedY, { align: 'right' });
      dedY += 6;
    });
  }

  y = Math.max(earnY, dedY) + 8;
  doc.setDrawColor(220, 220, 220);
  doc.line(left, y, 192, y);
  y += 11;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(5, 150, 105);
  doc.text('Net Salary', left, y);
  doc.text(formatAmount(payroll.net_salary), 192, y, { align: 'right' });
  doc.setTextColor(0, 0, 0);
  y += 12;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Status: ${String(payroll.status).toUpperCase()}`, left, y);
  if (payroll.paid_at) {
    doc.text(`Payment Date: ${new Date(payroll.paid_at).toLocaleDateString()}`, 110, y);
  }

  y += 14;
  doc.setFontSize(8.5);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by XERXEZ ERP', left, y);

  doc.save(`Payslip_${String(payroll.employee_name).replace(/\s+/g, '_')}_${MONTHS[payroll.month - 1]}_${payroll.year}.pdf`);
}
